#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1522106934                              # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The Music Sharing App

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Daniel Weatrowski
your_link                                 : https://danielweatrowski.com
your_city                                 : Fullerton, California
email_address                             : dweatrowski@gmail.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : dwweats
github_username                           : danielweatrowski
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Apple Music Integration
    description                           : Share a song directly from the Apple Music app without having to even open Yusic.
    fontawesome_icon_name                 : share-square
    
  - title                                 : Push Notifications
    description                           : Know when your friends share new songs to your Yusic library.
    fontawesome_icon_name                 : bell

  - title                                 : Spotify? No Problem
    description                           : While Yusic uses the Apple Music catalog of songs, Spotify or other music service users can still participate in viewing shared music.
    fontawesome_icon_name                 : play
    
  - title                                 : Share via iMessage or Email
    description                           : Share your Yusic library directly through messaging or email services. Friends and family with the Yusic app can accept the library to view your content instantly.
    fontawesome_icon_name                 : comment

  - title                                 : No Account Needed
    description                           : Download Yusic and start sharing right away. No need to sign in or sign up, Yusic handles this for you using iCloud.
    fontawesome_icon_name                 : user
    
  - title                                 : iCloud Integration
    description                           : Data is private and secured in your iCloud account. iCloud Sync allows for multiple devices to be up to date at all times.
    fontawesome_icon_name                 : cloud


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg              # Replace with alternative image path or image URL.
cover_overlay_color                       : "#007aff" #blue
cover_overlay_transparency                : 0.9

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#ff3b30" # red

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ff3b30" # red
feature_icons_background_color            : "rgba(255, 56, 46, 0.15)"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
